import type { GrowerProfile } from '@/utils/authToken';
import { isLocalhost } from '@/utils/env';

/** Localhost-only: open /dashboard/grower/* without login (dev preview). */
export const isGrowerLocalhostBypass = (): boolean => isLocalhost();

export const DEV_GROWER_PROFILE: GrowerProfile = {
    id: 'dev-localhost-grower',
    lyncId: 'GR-DEV-001',
    name: 'Kwame Mensah',
    status: 'active',
    region: 'Ashanti',
    district: 'Kumasi Metropolitan',
    community: 'Ejisu',
    email: 'grower.dev@localhost',
    contact: '+233 24 000 0001',
    gender: 'male',
    dob: '1988-04-12',
    language: 'Twi',
    ghanaCardNumber: 'GHA-123456789-0',
    farmType: 'mixed',
    farmSize: 2.5,
    yearsOfExperience: 8,
    landOwnershipStatus: 'owned',
    cropList: ['Cocoa', 'Maize'],
    cropsGrown: 'Cocoa, Maize',
    livestockInventory: [{ type: 'Poultry', count: 120 }],
    livestockType: 'Poultry (120)',
    farmLocation: { lat: 6.6885, lng: -1.6244, measuredAcres: 2.5 },
    currentStage: 'growing',
    profileCompleteness: 78,
    investmentStatus: 'Pending',
    investmentInterest: 'maybe',
    preferredInvestmentType: 'inputs',
    estimatedCapitalNeed: 15000,
    hasPreviousInvestment: false,
    investmentReadinessScore: 45,
    trainingModules: ['financial_lit', 'soil_crop'],
    verificationConfirmed: true,
    onboardingSource: 'self',
    onboardingAgentId: 'AG-DEV-001',
    fieldNotes: 'Demo grower profile for localhost preview.',
    investorBio: 'I grow cocoa and maize in Ejisu with eight years of experience. I follow good agricultural practices and work closely with my field agent.',
    growerStageNotes: { growing: 'Trees are healthy this season.' },
    profilePicture: 'https://api.dicebear.com/7.x/initials/svg?seed=Kwame%20Mensah',
    digitalCardNumber: 'AGL-C-48291037',
    digitalCardIssuedAt: '2024-06-01T00:00:00.000Z',
    digitalCardGenerated: true,
};

export const DEV_GROWER_STATS = {
    totalFarms: 2,
    activeCrops: 1,
    investorMatches: 0,
    activeInvestorMatches: 0,
    trainingSessions: 2,
    trainingModulesTotal: 5,
    agentVisitsCount: 3,
    daysSinceLastVisit: 14,
    totalEarnings: 0,
    currentStage: 'growing',
};

export const DEV_GROWER_FARMS = [
    {
        id: 'dev-farm-1',
        farmCode: 'FM-001',
        name: 'Cocoa Plantation 2024',
        crop: 'Cocoa',
        location: 'Ejisu, Ashanti',
        status: 'Growing',
        currentStage: 'growing',
    },
    {
        id: 'dev-farm-2',
        farmCode: 'FM-002',
        name: 'Poultry Farm Project',
        crop: 'Poultry',
        location: 'Kumasi, Ashanti',
        status: 'Active',
        currentStage: 'maintenance',
    },
];

export const DEV_GROWER_AGENT = {
    id: 'dev-agent-1',
    name: 'Ama Osei',
    contact: '+233 20 000 0002',
    email: 'agent.dev@localhost',
    agentId: 'AG-DEV-001',
    region: 'Ashanti',
    district: 'Kumasi',
};

const CROP_STAGES = [
    { key: 'land_preparation', label: 'Land Preparation', status: 'completed' as const },
    { key: 'planting', label: 'Planting', status: 'completed' as const },
    { key: 'growing', label: 'Growing', status: 'current' as const },
    { key: 'weeding', label: 'Weeding', status: 'pending' as const },
    { key: 'fertilizing', label: 'Fertilizing', status: 'pending' as const },
    { key: 'harvesting', label: 'Harvesting', status: 'pending' as const },
];

const LIVESTOCK_STAGES = [
    { key: 'brooding', label: 'Brooding', status: 'completed' as const },
    { key: 'growing', label: 'Growing', status: 'current' as const },
    { key: 'production', label: 'Production', status: 'pending' as const },
];

export const DEV_GROWER_FARM_PROFILE = {
    summary: {
        farmName: 'Cocoa Plantation 2024 & Poultry Farm Project',
        farmId: 'GR-DEV-001',
        farmSize: 2.5,
        measuredAcres: 2.5,
        gps: { lat: 6.6885, lng: -1.6244 },
        primaryActivity: 'mixed' as const,
        currentSeason: '2025',
        currentStage: 'growing',
        currentStageLabel: 'Growing',
        farmStatusFlag: 'on_track' as const,
        region: 'Ashanti',
        district: 'Kumasi Metropolitan',
        community: 'Ejisu',
    },
    rating: {
        stars: 4,
        proposedStars: 4,
        note: 'Strong training completion and good input compliance. Keep up weeding on schedule.',
        status: 'confirmed' as const,
        isConfirmed: true,
        isPendingReview: false,
    },
    pendingConfirmations: [
        {
            activityId: 'act-pending-1',
            farmId: 'dev-farm-1',
            farmName: 'Cocoa Plantation 2024',
            stage: 'growing',
            stageLabel: 'Growing',
            activityType: 'Fertilizer application',
            date: '2025-05-28',
            description: 'NPK applied on north section.',
        },
    ],
    farms: [
        {
            id: 'dev-farm-1',
            farmCode: 'FM-001',
            name: 'Cocoa Plantation 2024',
            crop: 'Cocoa',
            category: 'crop' as const,
            location: 'Ejisu, Ashanti',
            stageTracker: {
                farmId: 'dev-farm-1',
                farmCode: 'FM-001',
                farmName: 'Cocoa Plantation 2024',
                crop: 'Cocoa',
                category: 'crop' as const,
                currentStage: 'growing',
                stages: CROP_STAGES,
            },
        },
        {
            id: 'dev-farm-2',
            farmCode: 'FM-002',
            name: 'Poultry Farm Project',
            crop: 'Poultry',
            category: 'livestock' as const,
            location: 'Kumasi, Ashanti',
            stageTracker: {
                farmId: 'dev-farm-2',
                farmCode: 'FM-002',
                farmName: 'Poultry Farm Project',
                crop: 'Poultry',
                category: 'livestock' as const,
                currentStage: 'growing',
                stages: LIVESTOCK_STAGES,
            },
        },
    ],
    activities: [
        {
            id: 'act-1',
            farmId: 'dev-farm-1',
            farmName: 'Cocoa Plantation 2024',
            date: '2025-05-20',
            stage: 'growing',
            stageLabel: 'Growing',
            activityType: 'Field inspection',
            inputsUsed: '—',
            cost: null,
            hasPhoto: true,
            confirmationStatus: 'yes' as const,
        },
        {
            id: 'act-2',
            farmId: 'dev-farm-2',
            farmName: 'Poultry Farm Project',
            date: '2025-05-15',
            stage: 'growing',
            stageLabel: 'Growing',
            activityType: 'Feed distribution',
            inputsUsed: 'Starter feed (2 bags)',
            cost: 340,
            hasPhoto: false,
            confirmationStatus: 'yes' as const,
        },
        {
            id: 'act-pending-1',
            farmId: 'dev-farm-1',
            farmName: 'Cocoa Plantation 2024',
            date: '2025-05-28',
            stage: 'growing',
            stageLabel: 'Growing',
            activityType: 'Fertilizer application',
            inputsUsed: 'NPK 15-15-15',
            cost: 180,
            hasPhoto: true,
            confirmationStatus: 'pending' as const,
        },
    ],
    performance: {
        stagesCompleted: 3,
        trainingModulesCompleted: 2,
        trainingModulesTotal: 5,
        lastAgentVisit: '2025-05-20',
        rating: {
            stars: 4,
            proposedStars: 4,
            note: 'Strong training completion and good input compliance. Keep up weeding on schedule.',
            status: 'confirmed' as const,
            isConfirmed: true,
            isPendingReview: false,
        },
        farmStatusFlag: 'on_track' as const,
    },
};
