// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffdgcvxwrwirbqvspncu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmZGdjdnh3cndpcmJxdnNwbmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Mjc4NTEsImV4cCI6MjA1OTMwMzg1MX0.cm-Hdjn_8s9OCY5LHSWZRe70cjeg28WpaDVC4zWOkoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});